services:
  mathflix-frontend:
    image: ghcr.io/ferilee/mathflix:latest
    container_name: mathflix-frontend
    ports:
      - "9111:80"
    environment:
      - VITE_API_URL=/api
    restart: unless-stopped
